CREATE TABLE public.report_data (
                                    id uuid NOT NULL DEFAULT uuid_generate_v4(),
                                    outcome_id uuid NOT NULL,
                                    activity_type varchar(10) NULL,
                                    environment varchar(10) NULL,
                                    created_on timestamp NOT NULL,
                                    effective_disposable_surplus varchar(10) NULL,
                                    total_premium_value numeric(10, 2) NULL,
                                    is_funded bool NULL DEFAULT false,
                                    is_regulated bool NULL DEFAULT false,
                                    exclusion_reason varchar(20) NULL,
                                    customer_segment varchar(15) NULL,
                                    status varchar(15) NULL,
                                    decision_type varchar(10) NULL,
                                    business_line varchar(15) NULL,
                                    is_new bool NULL DEFAULT false,
                                    company_name varchar(50) NULL,
                                    company_number varchar(15) NULL,
                                    trader_type varchar(30) NULL,
                                    address_street varchar(50) NULL,
                                    address_country varchar(30) NULL,
                                    address_post_town varchar(30) NULL,
                                    address_postcode varchar(15) NULL,
                                    address_house_name varchar(30) NULL,
                                    address_house_number varchar(10) NULL,
                                    personal_title varchar(10) NULL,
                                    personal_surname varchar(30) NULL,
                                    personal_forename varchar(30) NULL,
                                    personal_middle_name varchar(30) NULL,
                                    personal_date_of_birth timestamp NULL,
                                    delphi_requested_on timestamp NULL,
                                    delphi_uuid_instance varchar(50) NULL,
                                    delphi_data_ndspcii varchar(10) NULL,
                                    delphi_data_e1b07 varchar(10) NULL,
                                    delphi_data_e1b08 varchar(10) NULL,
                                    delphi_data_ea1c01 varchar(10) NULL,
                                    delphi_data_ea4q05 varchar(10) NULL,
                                    delphi_data_e1a07 varchar(10) NULL,
                                    delphi_data_e1d02 varchar(10) NULL,
                                    delphi_data_e1b09 varchar(10) NULL,
                                    delphi_data_ndecc03 varchar(10) NULL,
                                    consumer_requested_on timestamp NULL,
                                    consumer_uuid_instance varchar(50) NULL,
                                    consumer_data_spedi03 varchar(10) NULL,
                                    consumer_data_spedi04 varchar(10) NULL,
                                    consumer_data_spedi05 varchar(10) NULL,
                                    consumer_data_spedi08 varchar(10) NULL,
                                    final_decision varchar(20) NULL,
                                    inclusion_outcome varchar(20) NULL,
                                    automated_decision varchar(20) NULL,
                                    final_create_on timestamp NULL,
                                    number_of_partners varchar(5) NULL,
                                    age int4 NULL,
                                    status_before varchar(20) NULL,
                                    agreement_number varchar(20) NULL,
                                    low_instalment varchar(3) NULL,
                                    income_expenditure varchar(10) NULL,
                                    agreement_serial int4 NULL,
                                    finance_instalment_amount numeric(10, 2) NULL,
                                    incorporation_status varchar(30) NULL,
                                    agreement_created_on timestamp NULL,
                                    automated_decision_date timestamp NULL,
                                    final_scheme_assigned varchar(20) NULL,
                                    automated_scheme_assigned varchar(20) NULL,
                                    CONSTRAINT report_data_pkey PRIMARY KEY (id)
);