package com.affordability.service.datafetcher;

import com.affordability.service.datafetcher.firstPartnerForCommercialAgreement.response.PartnerDetailsForCommercialAgreementQueryResponse;

public interface IPartnerDetailsForCommercialAgreement {

	PartnerDetailsForCommercialAgreementQueryResponse getFirstPartnerDetailsForCommercialAgreement(String agreementNumber);
}
